services:
  - type: web
    name: web_app
    env: python
    buildCommand: ./build.sh
    startCommand: waitress-serve app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NODE_VERSION
        value: 16.13.0